apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort    # == LoadBalancer (in aws, GCP, Azure)라고 적으면 된다.
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30004
  selector:
    app: myapp
